### ISSUE TITLE
Create a setup mode for users to initialize their good posture baseline (make it relative to user)

### ISSUE THREAD

**Issue by AndrewPBerg** [AndrewPBerg/posture-productivity#22]
# 1. Goal(s)
* Allow the user to graphically set their baseline posture and posture difficulty separate from the apps **main view**.
* Easily understood interface and dynamic output

# 2. Tasks
- [x] Add a setup button
- [x] Launch a pop-up window from button press
- [x] GUI that displays: [annotated image, extract posture button, Posture Rigidity slider]
- [x] Intuitive explanations for all of the UI

# 3. Technical Requirements
* SimplePyGUI popup window
* displaying annotated cv2 image
* getting sg values

# 4.  Notes

**Comment by AndrewPBerg** [comment]
Ended up using a combination of tab groups and columns!
