### ISSUE TITLE
Add standing boolean

### ISSUE THREAD

**Issue by AndrewPBerg** [AndrewPBerg/posture-productivity#29]
### Goals
Create/update is_standing function to accurately detect if user is standing. Should return bool

### Tasks
- [x] review current is standing boolean
- [x] add necessary landmarks to annotation
- [x] add necessary debug info
- [ ] 
### Technical
- [x] understand math conditionals behind standing bool
- [x] proper landmarks
