### ISSUE TITLE
Add work timer

### ISSUE THREAD

**Issue by AndrewPBerg** [AndrewPBerg/posture-productivity#30]
### Goals
Develop pomodoro style timer (3× variable_amount; with breaks) accessible via the settings tab

### Tasks

- [x] find py package to handle timer operations
- [x] create new timer settings tab
- [x] settings: [auto restart, break times, work times, reps, etc]
- [x] Move testing timer into main app window
- [x] Change popup "work cycle completed" to different notification method ~ Try a timed text box
- [x] sufficient explanation
### Tech
A python countdown timer package of sorts
GUI creation
