### ISSUE TITLE
Notify user of bad posture

### ISSUE THREAD

**Issue by AndrewPBerg** [AndrewPBerg/posture-productivity#6]
### 1. Goal(s)
Create a noticeable way to tell user that their posture is wrong

### 2. Tasks
- [ ] try windows notifications (that way it's configurable with do not disturb
- [ ] try popup window as notifications
- [x] try audio notifications
- [x] make sure notification isn't spamming or annoying (could count frames good frames + bad frames = total frames / FPS)
- [x] find notification audio track
- [ ] option to change notifications

### 3. Technical details
* popup windows
* system notification (could be system dependent)
* audio implementation

**Comment by AndrewPBerg** [comment]
### 1. Goal(s)
Create a noticeable way to tell user that their posture is wrong

### 2. Tasks
- [ ] try windows notifications (that way it's configurable with do not disturb
- [ ] try popup window as notifications
- [ ] try audio notifications
- [ ] make sure notification isn't spamming or annoying (could count frames good frames + bad frames = total frames / FPS)
- [ ] find notification audio track
- [ ] option to change notifications

### 3. Technical details
* popup windows
* system notification (could be system dependent)
* audio implementation
